### ISSUE TITLE
ddev - Elasticsearch Disk Watermark Warning on Mac M2 Pro Max with DDEV and Colima

### ISSUE THREAD

**Issue by lexsoft00** [wunderio/next-drupal-starterkit#274]
Hello everyone,

First off, thank you for this awesome example! It’s a wonderful starting point for learning Next.js, and I really appreciate all the hard work put into it.

I ran into a small snag when setting up on a Mac M2 Pro Max using DDEV and Colima. Elasticsearch threw the following warning and the installation script failed because of it:
`{"@timestamp":"2025-01-28T10:28:19.262Z", "log.level": "WARN", "message":"high disk watermark [90%] exceeded on [DEGDfhsNRlm6yFcGIDcCFQ][next-drupal-starterkit-elasticsearch][/usr/share/elasticsearch/data] free: 15.8gb[8.2%], shards will be relocated away from this node; currently relocating away shards totalling [0] bytes; the node is expected to continue to exceed the high disk watermark when these relocations are complete", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[next-drupal-starterkit-elasticsearch][masterService#updateTask][T#1]","log.logger":"org.elasticsearch.cluster.routing.allocation.DiskThresholdMonitor","elasticsearch.cluster.uuid":"g7dMeVeZTHibgRiCZ6-mnQ","elasticsearch.node.id":"DEGDfhsNRlm6yFcGIDcCFQ","elasticsearch.node.name":"next-drupal-starterkit-elasticsearch","elasticsearch.cluster.name":"docker-cluster"}`

I resolved this by lowering the disk watermarks:
```
curl -X PUT "elasticsearch:9200/_cluster/settings" \
  -H 'Content-Type: application/json' -d'
{
  "transient": {
    "cluster.routing.allocation.disk.watermark.low": "2gb",
    "cluster.routing.allocation.disk.watermark.high": "1gb",
    "cluster.routing.allocation.disk.watermark.flood_stage": "500mb",
    "cluster.info.update.interval": "1m"
  }
}'
```

A more permanent fix could be to include these settings in the Elasticsearch configuration under docker-compose.elasticsearch_extras.yaml, for example:

```
# ddev-generated
services:
  elasticsearch:
    environment:
      http.cors.enabled: "true"
      http.cors.allow-origin: "'*'"
      # Disable authentication in local development
      xpack.security.enabled: "false"
      xpack.security.enrollment.enabled: "false"
      cluster.routing.allocation.disk.watermark.low: "2gb"
      cluster.routing.allocation.disk.watermark.high: "1gb"
      cluster.routing.allocation.disk.watermark.flood_stage: "500mb"
      cluster.info.update.interval: "1m"
```

This ensures that Elasticsearch won’t hit the red status due to stricter default watermarks in a development environment.

Thanks again for this great example.
